import fs from 'node:fs';
import path from 'node:path';
import { FACTS, TOOLS, REPO, ROOT } from './facts.mjs';

const MARKER = '<!-- generated by scripts/readme/build.mjs. do not edit by hand. -->';

function pic(base, alt, width = true) {
  const w = width ? ' width="100%"' : '';
  return `<picture>
<source media="(max-width: 500px) and (prefers-color-scheme: dark)" srcset="assets/${base}-narrow-dark.svg">
<source media="(max-width: 500px)" srcset="assets/${base}-narrow-light.svg">
<source media="(prefers-color-scheme: dark)" srcset="assets/${base}-dark.svg">
<img alt="${alt}" src="assets/${base}-light.svg"${w}>
</picture>`;
}

const down = (FACTS.shotW / FACTS.exW).toFixed(3);
const heroExists = fs.existsSync(path.join(ROOT, 'assets/img/loop.png'));

// Sized to 76%, not full width: at full width the art pushes the install
// snippet under the fold on a laptop, and an install command below the fold is
// the one failure this page is not allowed to have.
const hero = heroExists
  ? `<p align="center">
<img alt="An isometric diagram of the loop: a desktop window is captured, downscaled for the model, and a click returns to a marked point on the original window." src="assets/img/loop.png" width="76%">
</p>

`
  : '';

const sigs = TOOLS.map(t => `| \`${t.name}(${t.params.join(', ')})\` |`).join('\n');

const DESCRIPTIONS = {
  screenshot: 'PNG of the primary monitor, downscaled',
  left_click: 'Click at a point',
  double_click: 'Two clicks at a point',
  triple_click: 'Three clicks, selects a line or paragraph',
  right_click: 'Context-menu click',
  middle_click: 'Middle-button click',
  mouse_move: 'Move the cursor without clicking',
  left_click_drag: 'Press, drag, release',
  type: 'Type at the current focus, non-ASCII goes through the clipboard',
  key: 'A key or chord: `enter`, `ctrl+s`, `alt+f4`',
  scroll: '`up`, `down`, `left`, `right`; horizontal is sent as shift+wheel',
  cursor_position: 'Where the mouse is now',
  record: `Sample the screen for up to ${FACTS.recordSeconds}s, up to ${FACTS.recordFrames} frames`,
  wait: `Pause before the next action, up to ${FACTS.waitSeconds}s`,
};

const missingDesc = TOOLS.filter(t => !DESCRIPTIONS[t.name]);
if (missingDesc.length) {
  console.error(`FAIL undescribed tools: ${missingDesc.map(t => t.name).join(', ')}`);
  process.exit(1);
}

const table = TOOLS.map(
  t => `| \`${t.name}(${t.params.join(', ')})\` | ${DESCRIPTIONS[t.name]} |`,
).join('\n');

const md = `${MARKER}
${hero}# winuse-mcp

Computer use for Claude Code on Windows. An MCP server that lets Claude see your screen and drive your mouse and keyboard.

Claude Code ships computer use in the CLI on macOS only, so on Windows the \`computer-use\` server never appears in \`/mcp\`. This rebuilds the same screenshot-and-click loop on the Windows APIs: ${FACTS.tools} tools, ${FACTS.deps} dependencies, Python ${FACTS.python}.

## Install

Needs Windows and [uv](https://docs.astral.sh/uv/). Add this to \`.mcp.json\` in a project, or to \`~/.claude.json\` for every project:

\`\`\`json
{
  "mcpServers": {
    "winuse": {
      "command": "uvx",
      "args": ["--from", "git+https://github.com/${REPO}", "winuse-mcp"]
    }
  }
}
\`\`\`

From a local clone instead:

\`\`\`json
{
  "mcpServers": {
    "winuse": {
      "command": "uv",
      "args": ["run", "--directory", "C:/path/to/winuse-mcp", "winuse-mcp"]
    }
  }
}
\`\`\`

Restart Claude Code, then ask it to look at your screen or click through an app.

## Reach

${pic('reach', `The ${FACTS.tools} tools, grouped: ${TOOLS.map(t => t.name).join(', ')}.`)}

<details>
<summary>Signatures</summary>

| Tool | Does |
|---|---|
${table}

Coordinates are always in screenshot space. See below.

</details>

## How coordinates work

${pic('transform', `A ${FACTS.exW} by ${FACTS.exH} screen captured as a ${FACTS.shotW} by ${FACTS.shotH} screenshot. Claude clicks at ${FACTS.modelX}, ${FACTS.modelY} in that image and the server fires the click at ${FACTS.nativeX}, ${FACTS.nativeY} on the real screen.`)}

Screenshots are downscaled so the long edge is at most ${FACTS.longEdge} pixels, the same target Claude Code uses on macOS. Claude never sees native pixels, so it clicks in the downscaled image and the server converts back.

A ${FACTS.exW}x${FACTS.exH} display captures at ${FACTS.shotW}x${FACTS.shotH}, a factor of ${down}. A click at ${FACTS.modelX}, ${FACTS.modelY} lands at ${FACTS.nativeX}, ${FACTS.nativeY}.

The server declares itself DPI-aware at startup, so Windows display scaling at 125% or 150% does not skew where clicks land.

## Safety

This hands a language model control of your desktop. Anthropic's own version wraps the same loop in guardrails this server does not have: per-app approval, hiding apps Claude has not been approved for, keeping your terminal out of the screenshots, and model-side checks on each action.

What you do get:

- Claude Code asks before each tool call unless you allow-list it. Keep the input tools on manual approval and only allow-list \`screenshot\`.
- Park the mouse in the top-left corner of the screen to abort the action in flight. That is pyautogui's failsafe, and it only watches that one corner. Aborting mid-drag releases the mouse button on the way out, so nothing is left dragging.
- Everything visible reaches the model, including whatever happens to be on screen. Text on screen is untrusted input: treat instructions that appear there as a prompt injection risk.

## Limitations

- Primary monitor only.
- Your terminal is not excluded from screenshots, so Claude sees its own session.
- \`record\` samples still frames, at most ${FACTS.recordFrames} of them. There is no video path.

## Development

\`\`\`bash
uv sync
uv run winuse-mcp
\`\`\`

\`scripts/client_test.py\` is the reference check: it speaks MCP over stdio to the server, lists the tools, takes a screenshot, moves the mouse and reads the position back, records frames, and asserts a bad key combo errors.

\`\`\`bash
uv run python scripts/client_test.py
\`\`\`

\`scripts/failsafe_test.py\` covers the paths a user hits while aborting, with pyautogui stubbed so no real abort is needed: a drag cut short still releases the button, a horizontal scroll cut short still releases shift, chord parsing handles a literal \`+\`, and no click can land on the failsafe pixel.

\`\`\`bash
uv run python scripts/failsafe_test.py
\`\`\`

This README is built. Every number on the page is recomputed from the source at build time, and the build fails if one drifts.

\`\`\`bash
node scripts/readme/build.mjs
\`\`\`

## License

MIT
`;

// ------------------------------------------------------------------ verify

let bad = 0;
const fail = m => {
  console.error(`FAIL ${m}`);
  bad++;
};

if (!md.startsWith(MARKER)) fail('generated marker missing from line 1');
if (!/^## Install$/m.test(md)) fail('install section missing');
if (!md.includes('"mcpServers"')) fail('install snippet missing');

// Every tool named exactly once in the signature table.
for (const t of TOOLS) {
  const hits = md.split(`\`${t.name}(`).length - 1;
  if (hits !== 1) fail(`${t.name}: ${hits} table rows`);
}

// Assets referenced must exist.
for (const m of md.matchAll(/(?:src|srcset)="((?:assets)\/[^"]+)"/g)) {
  if (!fs.existsSync(path.join(ROOT, m[1]))) fail(`missing asset ${m[1]}`);
}

// The install command is near the top, not buried under the art.
const installLine = md.split('\n').findIndex(l => l === '## Install');
if (installLine > 14) fail(`install section at line ${installLine}, too far down`);

if (bad) process.exit(1);

fs.writeFileSync(path.join(ROOT, 'README.md'), md);
console.error(
  `ok  README.md, ${TOOLS.length} tools linked once, install at line ${installLine}, hero ${heroExists ? 'present' : 'absent'}`,
);
